export interface StateInfo {
  name: string;
  code: string;
  avgTariffInr: number;
  discom: string;
  centralSubsidyEligible: boolean;
  stateSubsidyInrPerKw: number;
  netMeteringPolicy: "net_metering" | "gross_metering" | "avoided_cost" | "none";
  avgSunHoursDaily: number;
  solarZone: 1 | 2 | 3 | 4;
}

export const INDIAN_STATES: Record<string, StateInfo> = {
  "andhra_pradesh": {
    name: "Andhra Pradesh",
    code: "AP",
    avgTariffInr: 6.50,
    discom: "APEPDCL / APSPDCL",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 0,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 5.5,
    solarZone: 1,
  },
  "gujarat": {
    name: "Gujarat",
    code: "GJ",
    avgTariffInr: 5.80,
    discom: "DGVCL / MGVCL / PGVCL / UGVCL",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 10000,
    netMeteringPolicy: "gross_metering",
    avgSunHoursDaily: 5.8,
    solarZone: 1,
  },
  "maharashtra": {
    name: "Maharashtra",
    code: "MH",
    avgTariffInr: 8.50,
    discom: "MSEDCL / Tata Power / Adani",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 0,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 5.2,
    solarZone: 2,
  },
  "rajasthan": {
    name: "Rajasthan",
    code: "RJ",
    avgTariffInr: 6.20,
    discom: "JVVNL / AVVNL / JDVVNL",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 0,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 6.0,
    solarZone: 1,
  },
  "karnataka": {
    name: "Karnataka",
    code: "KA",
    avgTariffInr: 7.10,
    discom: "BESCOM / MESCOM / HESCOM / GESCOM / CESC",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 0,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 5.4,
    solarZone: 2,
  },
  "tamil_nadu": {
    name: "Tamil Nadu",
    code: "TN",
    avgTariffInr: 5.00,
    discom: "TANGEDCO",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 0,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 5.6,
    solarZone: 1,
  },
  "telangana": {
    name: "Telangana",
    code: "TS",
    avgTariffInr: 6.80,
    discom: "TSSPDCL / TSNPDCL",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 0,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 5.5,
    solarZone: 1,
  },
  "madhya_pradesh": {
    name: "Madhya Pradesh",
    code: "MP",
    avgTariffInr: 6.40,
    discom: "MPEZ / MPMKVVCL / MPMaKVVCL",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 0,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 5.5,
    solarZone: 1,
  },
  "uttar_pradesh": {
    name: "Uttar Pradesh",
    code: "UP",
    avgTariffInr: 6.00,
    discom: "PVVNL / DVVNL / PUVVNL / MVVNL",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 0,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 5.2,
    solarZone: 2,
  },
  "haryana": {
    name: "Haryana",
    code: "HR",
    avgTariffInr: 7.00,
    discom: "DHBVN / UHBVN",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 0,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 5.0,
    solarZone: 2,
  },
  "punjab": {
    name: "Punjab",
    code: "PB",
    avgTariffInr: 7.50,
    discom: "PSPCL",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 0,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 4.8,
    solarZone: 3,
  },
  "delhi": {
    name: "Delhi",
    code: "DL",
    avgTariffInr: 5.50,
    discom: "BSES Rajdhani / BSES Yamuna / Tata Power Delhi",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 2000,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 5.0,
    solarZone: 2,
  },
  "kerala": {
    name: "Kerala",
    code: "KL",
    avgTariffInr: 5.20,
    discom: "KSEB",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 0,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 4.5,
    solarZone: 3,
  },
  "west_bengal": {
    name: "West Bengal",
    code: "WB",
    avgTariffInr: 7.20,
    discom: "WBSEDCL / CESC",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 0,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 4.6,
    solarZone: 3,
  },
  "odisha": {
    name: "Odisha",
    code: "OD",
    avgTariffInr: 5.80,
    discom: "TPCODL / TPNODL / TPWODL / TPSODL",
    centralSubsidyEligible: true,
    stateSubsidyInrPerKw: 0,
    netMeteringPolicy: "net_metering",
    avgSunHoursDaily: 5.2,
    solarZone: 2,
  },
};

export const STATE_OPTIONS = Object.entries(INDIAN_STATES).map(([key, val]) => ({
  value: key,
  label: val.name,
}));

// India grid emission factor (kg CO2 per kWh) - CEA 2023
export const GRID_EMISSION_FACTOR = 0.82;
